---
- name: Ping google.com
  hosts: local
  tasks:
    - name: Ping google.com
      command: ping -c 4 bitbucket.mobitel.lk
      register: ping_output

    - name: Display the ping output
      debug:
        var: ping_output.stdout
